name: Lint

on:
  push:
  # Runs against the workflow and code from the merge commit
  pull_request:
    types: [ opened, synchronize, reopened ]
  # Runs against the workflow and code from the base of the pull request
  # pull_request_target:
    # types: [opened, synchronize, reopened]

env:
  DISABLE_PROGRESS: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: write-all
  
jobs:
  Lint:
    name: 🧠 ES Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check if user belongs to the organization
        id: check-org
        run: |
          ORG_NAME="xola"
          USER=$(jq -r .pull_request.user.login $GITHUB_EVENT_PATH)
          USER_ORG=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/users/$USER/orgs | jq -r ".[].login")
          if [[ "$USER_ORG" == "$ORG_NAME" ]]; then
            echo "User is a member of $ORG_NAME"
            echo ::set-output name=org-member::true
          else
            echo "User is not a member of $ORG_NAME"
            echo ::set-output name=org-member::false
            exit 1
          fi

      - name: Run workflow if user is in organization
        if: steps.check-org.outputs.org-member == 'true'
        run: |
          echo "User is in organization!"

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{github.event.pull_request.head.sha}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Node.JS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install Node Dependencies
        run: npm ci --no-fund --quiet --no-audit

      - name: Save Code Linting Report to JSON
        # This is to show failures in GitHub pull request using the action below
        run: npm run lint:report
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@2.2.0
        with:
          check-name: "View Lint Report"
          markdown-report-on-step-summary: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: "eslint_report.json"

#      # OPTIONAL: save a copy of the usage report for download or use in another job
#      # Save a copy of the usage report for download or use in another job
#      - name: Upload ESLint report
#        uses: actions/upload-artifact@v3
#        with:
#          name: eslint_report.json
#          path: eslint_report.json
